package evt

const (
	TextMessage                   Event = "text"
	ForwardMessage                Event = "forward_date"
	ReplyMessage                  Event = "reply_to_message"
	Animation                     Event = "animaition"
	Audio                         Event = "audio"
	Document                      Event = "document"
	Photo                         Event = "photo"
	Sticker                       Event = "sticker"
	Video                         Event = "video"
	Contact                       Event = "contact"
	Dice                          Event = "dice"
	Game                          Event = "game"
	Poll                          Event = "poll"
	Venue                         Event = "venue"
	Location                      Event = "location"
	NewChatMembers                Event = "new_chat_members"
	ChatMemberLeft                Event = "left_chat_member"
	NewChatTitle                  Event = "new_chat_title"
	NewChatPhoto                  Event = "new_chat_photo"
	ChatPhotoDeleted              Event = "delete_chat_photo"
	GroupChatCreated              Event = "group_chat_created"
	SuperGroupChatCreated         Event = "supergroup_chat_created"
	ChannelChatCreated            Event = "channel_chat_created"
	MessageAutoDeleteTimerChanged Event = "message_auto_delete_timer_changed"
	MigratedToChatId              Event = "migrate_to_chat_id"
	MigratedFromChatId            Event = "migrate_from_chat_id"
	MessagePinned                 Event = "pinned_message"
	Invoice                       Event = "invoice"
	SuccessfulPayment             Event = "successful_payment"
	ConnectedWebsite              Event = "connected_website"
	PassportData                  Event = "passport_data"
	ProximityAlert                Event = "proximity_alert_triggered"
	VideoChatScheduled            Event = "video_chat_scheduled"
	VideoChatStarted              Event = "video_chat_started"
	VideoChatEnded                Event = "video_chat_ended"
	VideoChatParticipantsInvited  Event = "video_chat_participants_invited"
	WebAppData                    Event = "web_app_data"
	ReplyMarkup                   Event = "reply_markup"
)
