package evt

const (
	TextMessage                   string = "Text"
	Command                       string = ""
	ForwardedMessage              string = ""
	Animation                     string = ""
	Audio                         string = ""
	Document                      string = ""
	Photo                         string = ""
	Stricker                      string = ""
	Video                         string = ""
	VideoNote                     string = ""
	Voice                         string = ""
	Contact                       string = ""
	Dice                          string = ""
	Game                          string = ""
	Poll                          string = ""
	Venue                         string = ""
	Location                      string = ""
	NewChatMember                 string = ""
	ChatMemberLeft                string = ""
	NewChatTitle                  string = ""
	NewChatPhoto                  string = ""
	ChatPhotoDeleted              string = ""
	GroupChatCreated              string = ""
	SuperGroupChatCreated         string = ""
	ChannelChatCreated            string = ""
	MessageAutoDeleteTimerChanged string = ""
	MigrateToChatId               string = ""
	MigrateFromChatId             string = ""
	PinnedMessage                 string = ""
	Invoice                       string = ""
	SuccessfulPayment             string = ""
	ConnectedWebsite              string = ""
	PassportData                  string = ""
	ProximityAlertTriggered       string = ""
	VideoChatCheduled             string = ""
	VideoChatStarted              string = ""
	VideoChatEnded                string = ""
	VideoChatParticipantsInvited  string = ""
	WebAppData                    string = ""
	ReplyMarkup                   string = ""
)
